Week 5 Day 3 : Milestone 5-6
Tekhlay/Module1-capstone-project pull request #3
Opened 2022-11-20 21:26 UTC by Tekhlay

### Milestone 5 Highlights 💯 

- [X] Implement the section "Featured speakers" with dynamic HTML.
- [X] Test the project for final approval readiness.

### Milestone 6 Highlights 👍 

- [X] Add a video explanation of the project
- [X] Update README.md file

2022-11-21 20:24 UTC, mgmediaweb requested changes
Hi @Tekhlay , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost1](https://user-images.githubusercontent.com/41912912/203142097-176b50d9-246d-4512-98b2-a31d166833d1.gif)

## Highlights 💯 
- Professional-looking readme file. ✔️ 
- Clear and descriptive Pull Request. ✔️ 
- Clean and tidy code. ✔️ 
- Good job following the design. ✔️ 

## Required Changes ♻️

- Kindly, I will modify you to review some important points of your presentation video, this should not last more than 5 minutes, the version of the page that you present is not the same as the one that is displayed, and finally, you do not indicate which one is the part of your presentation that gives you the most pride, consider it and send us a new video!

- Kindly, the main idea of this exercise is that the student bases himself on the design of the site but adapts it to his own theme, personally, I see a lot of content from the original design, texts, images, and logos, perhaps you could put more content made by you.

- Kindly, I suggest that when you use an "A" tag, indicate some link in the HREF attribute, if you don't have any valid link, use a "#" symbol instead.
index.html lines 18 - 22
about.html lines 18 - 22

- Kindly suggest when you create a paragraph use a p tag (lowercase)
index.html lines 59 - 63
about.html lines 59 - 65

- Kindly, I suggest you use only 1 CSS file for both pages (Homepage, About), it will be much easier to maintain in case you need to make changes you only do it in 1 file and not 2. A special CSS file is used in addition to the normal (style.css) if you need some kind of exclusive style for that page, but in addition to the base CSS, I hope I have been clear.

- Kindly, suggest that the white border you see on the card is the sample of how it should look in HOVER mode, so any of the Cards should have those user interactions.
![image](https://user-images.githubusercontent.com/41912912/203148664-67c0be08-f4a1-4a0b-815c-d6f196f6a46e.png)

- Kindly, I suggest you update the displayed version of your website, this one in the mobile menu (inside the About page), does not have the Home button to return to the beginning
![image](https://user-images.githubusercontent.com/41912912/203146408-3a01e171-2025-4daf-bc08-8b68ce5c6647.png)

- Kindly, I suggest you modify your CSS code so that the images adapt proportionally to the size of the device and do not distort (a tip do not use height at 100%)
![image](https://user-images.githubusercontent.com/41912912/203147452-1e3553e6-aa91-4287-a4ac-50aa65616b16.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Kindly, I suggest you review why a horizontal scroll is generated
![image](https://user-images.githubusercontent.com/41912912/203146928-0f02c14c-d3d7-4a0d-96b6-482a9a6bbb7e.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-21 20:24 UTC, mgmediaweb commented on index.html
>              <div class="program">
Kindly, I suggest when you use boilerplate code, it is better to use "ARTICLE" semantic tag, your code will be more understandable and more professional.

2022-11-21 20:24 UTC, mgmediaweb commented on index.html
>              <div class="program">
Kindly, I suggest when you use boilerplate code, it is better to use "ARTICLE" semantic tag, your code will be more understandable and more professional.

2022-11-21 20:24 UTC, mgmediaweb commented on index.html
>              <div class="program">
Kindly, I suggest when you use boilerplate code, it is better to use "ARTICLE" semantic tag, your code will be more understandable and more professional.

2022-11-21 20:24 UTC, mgmediaweb commented on index.html
>              <div class="program">
Kindly, I suggest when you use boilerplate code, it is better to use "ARTICLE" semantic tag, your code will be more understandable and more professional.

2022-11-21 20:24 UTC, mgmediaweb commented on js/index.js
> +    const speaker = document.createElement('div');
Kindly, I suggest when you use boilerplate code, it is better to use "ARTICLE" semantic tag, your code will be more understandable and more professional.

2022-11-21 20:24 UTC, mgmediaweb commented on js/index.js
> +    const speaker = document.createElement('div');
Kindly, I suggest when you use boilerplate code, it is better to use "ARTICLE" semantic tag, your code will be more understandable and more professional.

2022-11-21 20:24 UTC, mgmediaweb commented on js/index.js
> +const displaytwo = () => {
[OPTIONAL] It would be great if instead of using 2 functions that list the "speakers" (which only differentiates the number of elements to display), that you reuse the same function and pass the number of elements to display by parameters, consider it, it will do see your code much more pro!

2022-11-21 20:24 UTC, mgmediaweb commented on js/index.js
> +const displayAll = () => {
[OPTIONAL] It would be great if instead of using 2 functions that list the "speakers" (which only differentiates the number of elements to display), that you reuse the same function and pass the number of elements to display by parameters, consider it, it will do see your code much more pro!

2022-11-22 18:02 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Tekhlay 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
- [ ] As mentioned by the previous reviewer, kindly include a piece of code that you're proud of in the presentation video 👍 

_Kindly check the comments below_

## Optional:
_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-22 18:02 UTC, ha-manel commented on index.html
>              <h3>"Hello Digital World"</h3>
[Optional]

- [ ] Kindly fix the header issue. In mobile version it overlaps on itself 👍 

![image](https://user-images.githubusercontent.com/50721479/203387846-ef2fde69-539d-45f3-b122-27a2998a0330.png)

2022-11-23 11:32 UTC, Santiago220991 approved these changes
Hi @Tekhlay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
:heavy_check_mark: Applied changes suggested by the last reviewer,
:heavy_check_mark: Followed GitHub flow.
:heavy_check_mark: Good commit messages.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 11:34 UTC, merged